CRUD/Models/Order.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace CRUD.Models;

[Index(nameof(Number), nameof(ProviderId), IsUnique = true)]
public class Order
{
    public int Id { get; set; }
    [DisplayName("Номер заказа")]
    public string Number { get; set; }
    [DisplayName("Дата заказа")]
    [DataType(DataType.Date)] 
    public DateTime Date { get; set; }
    [DisplayName("Поставщик")]
    public int ProviderId { get; set; }
    public Provider? Provider { get; set; }
}

CRUD/Controllers/OrderController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRUD.Data;
using CRUD.Data.Abstract;
using CRUD.Models;
using CRUD.ViewModels;

namespace CRUD.Controllers
{
    public class OrderController : Controller
    {
        //private readonly EFDbContext _context;
        private EFDbContext _context;

        public OrderController(EFDbContext context)
        {
            _context = context;
        }

        // GET: Order
        public async Task<IActionResult> Index(string sortOrder, DateTime? startDate, DateTime? endDate, string? selectedNumber, int? selectedProvider)
        {
            ViewData["NumSortPar"] = String.IsNullOrEmpty(sortOrder) ? "num_desc" : "";
            ViewData["DateSortPar"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["StartDate"] = startDate;
            ViewData["EndDate"] = endDate;

            ViewData["Numbers"] = new SelectList(_context.Order
                .GroupBy(c=>c.Number)
                .Select(s => s.First()), "Id", "Number");
            
            ViewData["Providers"] = new SelectList(_context.Provider
                .GroupBy(c=>c.Name)
                .Select(s => s.First()), "Id", "Name");
            
            ViewData["Items"] = new SelectList(_context.OrderItem
                .GroupBy(c=>c.Name)
                .Select(s => s.First()), "Id", "Name");
            
            ViewData["Units"] = new SelectList(_context.OrderItem
                .GroupBy(c=>c.Unit)
                .Select(s => s.First()), "Id", "Unit");
            
            IQueryable<Order> orders = _context.Order
                .Include(o => o.Provider);
            
            if (startDate != null && endDate != null)
            {
                orders = orders.Where(s => s.Date < endDate 
                && s.Date > startDate);
            }
            
            if (selectedNumber != null)
            {
                orders = orders.Where(s => s.Number == selectedNumber);
            }
            
            if (selectedProvider != null)
            {
                orders = orders.Where(s => s.ProviderId == selectedProvider);
            }
            
            switch (sortOrder)
            {
                case "num_desc":
                    orders = orders.OrderByDescending(s => s.Number);
                    break;
                case "Date":
                    orders = orders.OrderBy(s => s.Date);
                    break;
                case "date_desc":
                    orders = orders.OrderByDescending(s => s.Date);
                    break;
                default:
                    orders = orders.OrderBy(s => s.Number);
                    break;
            }
            return View(await orders.AsNoTracking().ToListAsync());
        }

        // GET: Order/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            OrderItemsViewModel orderAndItems = new OrderItemsViewModel()
            {
                Order = _context.Order
                    .Include(o => o.Provider)
                    .FirstOrDefault(m => m.Id == id),
                OrderItems = _context.OrderItem
                    .Where(s=>s.OrderId == id).ToList()
            };
            //orderAndItems.OrderItems = orderAndItems.OrderItems.Where(s => s.OrderId == id);
            if (orderAndItems.Order == null)
            {
                return NotFound();
            }

            return View(orderAndItems);
        }

        // GET: Order/Create
        public IActionResult Create()
        {
            ViewData["Providers"] = new SelectList(_context.Provider, "Id", "Name");
            return View();
        }

        // POST: Order/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Order order)
        {
            var orderCheck = _context.Order
                .Any(n => n.Number == order.Number && n.ProviderId == order.ProviderId);
            
            if (ModelState.IsValid)
            {
                if (!orderCheck)
                {
                    _context.Add(order);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError(nameof(order.Number), "У данного поставщика уже есть заказ с таким номером");
                    ViewData["Providers"] = new SelectList(_context.Provider, "Id", "Name");
                    return View(order);
                }
            }
            return View(order);
        }
        
        // GET: Order/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewData["Providers"] = new SelectList(_context.Provider, "Id", "Name");
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            OrderItemsViewModel orderAndItems = new OrderItemsViewModel()
            {
                Order = _context.Order
                    .FirstOrDefault(m => m.Id == id),
                OrderItems = _context.OrderItem
                    .Where(s=>s.OrderId == id).ToList()
            };
            if (orderAndItems.Order == null)
            {
                return NotFound();
            }
            return View(orderAndItems);
        }
        
        // POST: Order/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, OrderItemsViewModel orderAndItems)
        {
            if (id != orderAndItems.Order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orderAndItems.Order);
                    await _context.SaveChangesAsync();

                    foreach (var o in orderAndItems.OrderItems)
                    {
                        _context.Update(o);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(orderAndItems.Order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
            //return View(orderAndItems);
        }

        // GET: Order/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = _context.Order
                .FirstOrDefault(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Order == null)
            {
                return Problem("Entity set 'CRUDContext.Order'  is null.");
            }
            var order = await _context.Order.FindAsync(id);
            if (order != null)
            {
                _context.Remove(order);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
          return (_context.Order?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CRUD/Controllers/OrderItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRUD.Data;
using CRUD.Models;

namespace CRUD.Controllers
{
    public class OrderItemController : Controller
    {
        private readonly EFDbContext _context;

        public OrderItemController(EFDbContext context)
        {
            _context = context;
        }

        // GET: OrderItem
        public async Task<IActionResult> Index()
        {
            var eFDbContext = _context.OrderItem.Include(o => o.Order);
            return View(await eFDbContext.ToListAsync());
        }

        // GET: OrderItem/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.OrderItem == null)
            {
                return NotFound();
            } 

            var orderItem = await _context.OrderItem
                .Include(o => o.Order)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orderItem == null)
            {
                return NotFound();
            }

            return View(orderItem);
        }

        // GET: OrderItem/Create
        public IActionResult Create(int orderId)
        {
            //ViewData["OrderId"] = orderId;
            OrderItem item = new OrderItem();
            item.OrderId = orderId;
            return View(item);
        }

        // POST: OrderItem/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OrderItem orderItem)
        {
            var checkOrder = _context.Order
                .Any(n => n.Id == orderItem.OrderId && n.Number == orderItem.Name);

            if (ModelState.IsValid)
           {
               if (!checkOrder)
               {
                   _context.Add(orderItem);
                   await _context.SaveChangesAsync();
                   return RedirectToAction("Edit", "Order", new {id = orderItem.OrderId});
               }
               else
               {
                   var order = _context.Order
                       .First(n => n.Id == orderItem.OrderId && n.Number == orderItem.Name);

                   ModelState.AddModelError(nameof(orderItem.Name),
                       "Наименование товара не может быть равно номеру заказа (" + order.Number + ")");
                   ViewData["Providers"] = new SelectList(_context.Provider, "Id", "Name");
                   //ViewData["OrderId"] = ;
                   return View(orderItem);
               }
           }
            return View(orderItem);
        }

        // GET: OrderItem/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.OrderItem == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItem.FindAsync(id);
            if (orderItem == null)
            {
                return NotFound();
            }
            ViewData["OrderId"] = new SelectList(_context.Order, "Id", "Id", orderItem.OrderId);
            return View(orderItem);
        }

        // POST: OrderItem/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,OrderId,Name,Quantity,Unit")] OrderItem orderItem)
        {
            if (id != orderItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orderItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderItemExists(orderItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderId"] = new SelectList(_context.Order, "Id", "Id", orderItem.OrderId);
            return View(orderItem);
        }

        // GET: OrderItem/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.OrderItem == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItem
                .Include(o => o.Order)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orderItem == null)
            {
                return NotFound();
            }

            return View(orderItem);
        }

        // POST: OrderItem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.OrderItem == null)
            {
                return Problem("Entity set 'EFDbContext.OrderItem'  is null.");
            }
            var orderItem = await _context.OrderItem.FindAsync(id);
            if (orderItem != null)
            {
                _context.OrderItem.Remove(orderItem);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction("Edit","Order", new { id = orderItem.OrderId });
        }

        private bool OrderItemExists(int id)
        {
          return (_context.OrderItem?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CRUD/Views/Order/Create.cshtml
@model CRUD.Models.Order

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Создание нового заказа</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <h4>Номер заказа</h4>
                <input asp-for="Number" class="form-control"/>
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <p/>
            <div class="form-group">
                <h4>Дата</h4>
                <input asp-for="Date" class="form-control"/>
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <p/>
            <div class="form-group">
                <h4>Поставщик</h4>
                <select asp-for="ProviderId" class ="form-control" asp-items="ViewBag.Providers"></select>
            </div>
            <p/>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<p/>
<div>
    <a asp-action="Index">К списку заказов</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRUD/Views/Order/Delete.cshtml
@model CRUD.Models.Order

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProviderId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProviderId)
        </dd>
    </dl>
    
    <form asp-controller="Order" asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CRUD/Views/Order/Details.cshtml
@using CRUD.Models
@model CRUD.ViewModels.OrderItemsViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Детали заказа</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Order.Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Order.Number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Order.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Order.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Order.ProviderId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Order.Provider.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Order.Id">Редактировать</a> |
    <a asp-action="Delete" asp-route-id="@Model?.Order.Id">Удалить</a> |
    <a asp-action="Index">К списку заказов</a>
</div>

<table class="table">
    <thead>
        <tr>
            <td>Наименование</td>
            <td>Модель</td>
            <td>Количество</td>
        </tr>
    </thead>
<tbody>
@foreach (var item in Model.OrderItems)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Unit)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)

        </td>
    </tr>
}
 </tbody>
</table>

CRUD/Views/Order/Edit.cshtml
@model CRUD.ViewModels.OrderItemsViewModel

@{
    ViewData["Title"] = "Редактирование заказа";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Редактирование заказа</h1>

<hr/>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div class="row">
        <form asp-controller="Order" asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-md-4">
                <input type="hidden" asp-for="Order.Id"/>
                <div class="form-group">
                    <h4>Номер заказа</h4>
                    <input asp-for="Order.Number" class="form-control"/>
                    <span asp-validation-for="Order.Number" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <p/>
                    <h4>Дата</h4>
                    <input asp-for="Order.Date" class="form-control"/>
                    <span asp-validation-for="Order.Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <p/>
                    <h4>Поставщик</h4>
                    <select asp-for="Order.ProviderId" class ="form-control" asp-items="ViewBag.Providers"></select>
                </div>
            </div>
            <p/>
            <h3>Товары</h3>
            <div class="col-md-10">
                <table id="orderItems" class="table table-hover table-responsive-sm display">
                    <thead>
                    <tr>
                        <th>
                            <h4>№</h4>
                        </th>
                        <th>
                            <h4>Наименование</h4>
                        </th>
                        <th>
                            <h4>Модель</h4>
                        </th>
                        <th>
                            <h4>Количество</h4>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    @for (int i = 0; i < Model.OrderItems.Count(); i++)
                    {
                        <tr>
                            <input type="hidden" asp-for="@Model.OrderItems[i].Id"/>
                            <input type="hidden" asp-for="@Model.OrderItems[i].OrderId"/>
                            <td>@(i + 1)</td>
                            <td>
                                <input asp-for="@Model.OrderItems[i].Name" class="form-control"/>
                                <span asp-validation-for="@Model.OrderItems[i].Name" class="text-danger"></span>
                            </td>
                            <td>
                                <input asp-for="@Model.OrderItems[i].Unit" class="form-control"/>
                                <span asp-validation-for="@Model.OrderItems[i].Unit" class="text-danger"></span>
                            </td>
                            <td>
                                <input asp-for="@Model.OrderItems[i].Quantity" class="form-control"/>
                                <span asp-validation-for="@Model.OrderItems[i].Quantity" class="text-danger"></span>
                            </td>
                            <td>
                                <button type="button" class="btn btn-light" onclick="location.href='@Url.Action("Delete", "OrderItem", new { id = Model.OrderItems[i].Id} )'">&#10060;</button>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
            <div>
                <button type="button" class="btn btn-light" onclick="location.href='@Url.Action("Create", "OrderItem", new { orderId = Model.Order.Id} )'">&#10133 Добавить товар</button>
            </div>
            <p/>
            <div class="form-group">
                <input type="submit" value="&#x1F4BE; Сохранить" class="btn btn-primary"/>
            </div>
        </form>
    </div>
}
    <br/>

    <div>
        <a asp-action="Index">К списку заказов</a>
    </div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRUD/Views/Order/Index.cshtml
@model IEnumerable<CRUD.Models.Order>

@{
    ViewData["Title"] = "Заказы";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Заказы</h1>

<h4>Фильтры</h4>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Номер заказа: <select name="selectedNumber" asp-items="ViewBag.Numbers">
                <option value="">---</option>
            </select>&nbsp;
            Поставщик: <select name="selectedProvider" asp-items="ViewBag.Providers">
                <option value="">---</option>
            </select>
            Наименование товара: <select name="selectedItem" asp-items="ViewBag.Items">
                <option value="">---</option>
            </select>
            Модель товара: <select name="selectedUnit" asp-items="ViewBag.Units">
                <option value="">---</option>
            </select>
        </p>
        <p>
            Начальная дата: <input type="date" name="startDate" value=@DateTime.Today.AddMonths(-1).ToString("yyyy-MM-dd")/>&nbsp; &nbsp;
            Конечная дата: <input type="date" name="endDate" value="@DateTime.Today.ToString("yyyy-MM-dd")"/>&nbsp; &nbsp;
            <input type="submit" value="Применить" class="btn btn-info" style="color:white"/> &nbsp; | &nbsp;
            <a asp-action="Index">Сбросить</a>
        </p>
    </div>
</form>

<div>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Create", "Order" )'">&#43 Создать новый заказ</button>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NumSortPar"]">Номер заказа</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortPar"]">Дата создания</a>
            </th>
            <th>
                Поставщик
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr onclick="location.href = '@Url.Action( "Details", "Order", new { id=@item.Id})'">
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Provider.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Редактировать</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Детали</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>